### ISSUE TITLE
Build Error: No such file or directory

### ISSUE THREAD

**Issue by Zheng-Tong** [CoRE-RG/CoRE4INET#10]
Hello Core Group,

I got a fatal error when the project is built by GCC on windows 10 with OMNeT++ 5.3.

Error information: core4inet/api/base/Callback.cc:17:10: fatal error: core4inet/api/base/Callback.h: No such file or directory  #include "core4inet/api/base/Callback.h".

I can fix the bug by changing  `#include "core4inet/api/base/Callback.h"` to `#include "Callback.h"`. But there are many other similar bugs, is there any good way?

Thanks and Regards,
Tong

**Comment by Musteblume** [comment]
Our models are currently adapted for OMNeT++ 5.5.1 and INET 3.6.6. I would recommend to use this newer Version of OMNeT++.

**Comment by Zheng-Tong** [comment]
Cool！It works！ Thank you very much!
