### ISSUE TITLE
AVB EtherHost and EtherSwitch node

### ISSUE THREAD

**Issue by bsaivarun** [CoRE-RG/CoRE4INET#17]
Hello CoRE4INET group,

I am working on a network simulation where I have AVB SR class A, B and BE traffic. I want to know whether it will be appropriate to use the TTEAVBEtherSwitch, and TTEAVBEtherHost nodes for this simulation? TTEAVBEtherSwitch and TTEAVBEtherHost  nodes support TT and AVB traffic both. But in my simulation I do not have TT traffic. So, could anyone of you please clarify if it makes sense to use TTEAVBEtherSwitch, and TTEAVBEtherHost.

Thanks,

**Comment by Musteblume** [comment]
Hello,
yes you can just use this nodes. If there is no TT traffic configured they behave like AVB class A is the highest priority.
Regrads 
Philipp

**Comment by bsaivarun** [comment]
Thank you for your quick response.

I have another doubt and it will be helpful to me if you could clarify this.

Below figure is of the TTEAVBEtherSwitch. In the switch it is mentioned that the avbABuffer, and avbBBuffer represents a queue buffer for time-triggered traffic. So, if I understood this correctly, these two buffers are only required for the TT traffic and not for the AVB traffic. 

![switch](https://user-images.githubusercontent.com/29229741/86370424-055c6b00-bc80-11ea-8ef1-73c45d8d9ad3.JPG)

It will be helpful to me if you could explain what is the use of these two buffers.

Thanks and Regards

**Comment by Musteblume** [comment]
Hi,
this is wrong. This buffers are only for AVB class A and B traffic. 
Where did you find this description exactly?
You are welcome.
Regards
Philipp

**Comment by bsaivarun** [comment]
Hi,

It is given in the description.

![avbBuffer](https://user-images.githubusercontent.com/29229741/86373839-26bf5600-bc84-11ea-96ea-efeffd3f8b91.JPG)

Thanks for the clarification.

**Comment by Musteblume** [comment]
Thank you for the hint, i will fix that description
