### ISSUE TITLE
Issue in "dropped" signal

### ISSUE THREAD

**Issue by franc444** [CoRE-RG/CoRE4INET#19]
Hi, 

I got the following error when I tried limiting the size of AVBQueue buffer: 

`omnetpp::SumRecorder: Cannot convert cObject * to double while processing statistic signal dropped (id=207) with data type CoRE4INET::AVBFrame`

**Comment by Musteblume** [comment]
Hi,

thank you for reporting. I have fixed the issue and it should be released here in the next 24h.
