### ISSUE TITLE
AVBFrame size

### ISSUE THREAD

**Issue by ZoltanBojthe** [CoRE-RG/CoRE4INET#2]
The AVBFrame size equal to EthernetIIFrameWithQTag.
Missing the byteLength setting in AVBFrame.msg or AVBTrafficSourceApp::sendAVBFrame().

**Comment by Musteblume** [comment]
Hi,
EthernetIIFrameWithQTag is the base of AVBFrame. Therefore the byteLength configured in EthernetIIFrameWithQTag.msg is the same for AVBFrame

**Comment by ZoltanBojthe** [comment]
The AVBFrame contains a 64 bit length `streamID` field (declared in msg file). Where stored this data if the frame length equal to EthernetIIFrameWithQTag?

**Comment by Musteblume** [comment]
This field is not stored in a real AVB frame. In a real network the streamid is identified just through the multicast destination mac address.
