### ISSUE TITLE
How to extend TSN example with FlowMetering?

### ISSUE THREAD

**Issue by CC-vga** [CoRE-RG/CoRE4INET#23]
Hi, 

I would like to extend the TSN example to use also FlowMetering. Node1 generates 2 streams now, one is TS and one is AVB. And I have 2 questions:
1. Why when I define the FlowMeter for AVB stream on switch1, I get the following error:
`<!> Error: Cannot convert inf to simtime_t: Out of range (-9223372.036854775807,9223372.036854775807), allowed by scale exponent -12 -- in module (CoRE4INET::CreditBasedMeter) small_network.switch1.phy[0].filtering.flowMeter[1] (id=210), at t=0.00006376s, event #342
undisposed object: (CoRE4INET::SchedulerTimerEvent) small_network.switch1.phy[0].filtering.flowMeter.CBM_SENDSLOPE_END -- check module destructor`
Can someone help me please to fix this error?
2. How I can define  custom Committed Information Rate (CIR) for the meter? Let’s say that I would like to have a CIR of 1000B per 200us.

All best
Voica

**Comment by THaeckel** [comment]
Hello Voica, 
The TSN example network also has a configuration for FlowMeters. Do you get any errors when running the TSN example? 
Otherwise, it might be some kind of configuration problem or a bug, so we might need more information such as ini file configurations and network topology.

I have assigned Philipp (Musteblume) to this question and hope he can help you. Currently, he is on vacation, but he will get in touch as soon as he is back. Thanks for your patience.

Best
Timo

**Comment by CC-vga** [comment]
Hi Timo, 

Thanks for reaching back! Until Philipp is back, here are some details:
TSN example works with configuration "With_Qci". Though, this configuration is just using filtering and gating, but not flow metering. 
Or there is another TSN example that has also a configuration defining CreditBasedMeters?

All best
Voica

**Comment by Musteblume** [comment]
Hi Voica,

Regarding the CIR: The CreditBasedMeter is an experimental creation by us which is not defined in the standard. The token bucket based metering from the standard which uses CIR etc. is not implemented. You can implement a token based approach by extending IEEE8021QciMeter.

Regarding the Error: Are you still getting the error? Can you show the configuration that produces the error?

Best regards
Philipp

**Comment by CC-vga** [comment]
Hi Philipp,

Thank you for the clarification about the non-standard CIR implementation! After removing the flow meter, the error disappears :)

All best
Voica

**Comment by Musteblume** [comment]
Hi Voica,

that's good news but it should also not crash when using the flow meter. Are you able to share your crashing configuration with me? It would be valuable to fix this.

Best regards
Philipp

**Comment by CC-vga** [comment]
Hi Philipp, 

Hoping that helps, I’m attaching the switch configuration (switch1.txt) adapted from TSN example! Error message is as in the first comment, first point,  of this thread.
There is another problem; I ended-up with 2 StreamGate and FlowMeter instances, since having only one customized instance per-port  also crashed.
If you need more details, please feel free to reach out! 

All best
Voica
[switch1.txt](https://github.com/CoRE-RG/CoRE4INET/files/7136095/switch1.txt)

**Comment by Musteblume** [comment]
Hi Voica,

thank you very much. I will have a deeper look into the issue.

Best regards
Philipp

**Comment by Musteblume** [comment]
Hi,

was able to recreate the error:

The cause was a misconfiguration of the stream filter:
```
**.switch1.phy[0].filtering.streamFilter[1].typename = "QTagFilter"
**.switch1.phy[0].filtering.streamFilter[1].vID = 2
**.switch1.phy[0].filtering.streamFilter[1].pcp = 6
**.switch1.phy[0].filtering.streamFilter[1].srcAddress = "0A-00-00-00-00-01"
**.switch1.phy[0].filtering.streamFilter[1].gateID = 1
**.switch1.phy[0].filtering.streamFilter[1].meterID = 1 
**.switch1.phy[0].filtering.flowMeter[1].typename = "CreditBasedMeter"
**.switch1.phy[0].filtering.flowMeter[1].maxBurst = 1
```
But the source of the stream is `**.node2.phy[*].mac.address = "0A-00-00-00-00-02"`

This results in CreditBasedMeter thinking zero bandwidth is reserved for the stream.
I fixed that CBM is not crashing on zero bandwidth. Now, it doesn't crash on misconfiguration.
Thank you for the info's.

Best regards
Philipp

**Comment by CC-vga** [comment]
Hi Philipp,

Thank you for finding out the misconfiguration! On which version is fixed now the 0-bw problem in CBM?

All best
Voica
________________________________

**Comment by Musteblume** [comment]
Hi Voica,

should be published here in the master branch today.

Best regards
Philipp

**Comment by Musteblume** [comment]
Fix is published in master.
