### ISSUE TITLE
Copy-paste bug in IPv4oREBase.cc

### ISSUE THREAD

**Issue by ZoltanBojthe** [CoRE-RG/CoRE4INET#3]
https://github.com/CoRE-RG/CoRE4INET/blob/56f1f648565f8220ce7d6dc8e63aeb0dc2eab350/src/core4inet/networklayer/inet/base/IPv4oREBase.cc#L67

`destPrefixLength` is invalid

**Comment by Musteblume** [comment]
Thank you for reporting.
