### ISSUE TITLE
Question - "One talker node with MAC address "0A-00-00-00-00-00" is sending two different flows to the same listener with MAC address "0A-00-00-00-00-01". The vids are different for the flows.

### ISSUE THREAD

**Issue by Kamalakannan23** [CoRE-RG/CoRE4INET#44]
Hi,

Question - "One talker node with MAC address "0A-00-00-00-00-00" is sending two different flows to the same listener with MAC address "0A-00-00-00-00-01". The vids are different for the flows.

But why in the listener node, the two traffic sink apps (app[0] and app[1]) accepts both flows from the talker? Whereas, one traffic sink is for one flow and other traffic sink is for the another flow.

I am using the IEEE8021QTrafficSinkApp app. In the code attached below, in the handleMessage, only the source address is checked and not the vid. How to handle this scenario?

void IEEE8021QTrafficSinkApp::handleMessage(cMessage *msg)
{
if (EthernetIIFrameWithQTag qframe = dynamic_cast<EthernetIIFrameWithQTag>(msg)){
if ((address.isUnspecified() || qframe->getSrc() == address)){
int pcp = qframe->getPcp();
emit(this->rxQPcpPkSignals[pcp], qframe);
}
}
BGTrafficSinkApp::handleMessage(msg);
}
![image](https://user-images.githubusercontent.com/61795091/182630185-a61584bd-cbad-4ee2-bd2c-fa4487c78ef5.png)

**Comment by Musteblume** [comment]
Hi,

yes it would be nicer if the QSinkApp would have a parameter to set the vid that traffic it wants to consume is tagged with.
I have added this parameter. Should be part of the next nightly release.

Also attached the changed files of the IEEE8021QTrafficSink:
[IEEE8021Q.zip](https://github.com/CoRE-RG/CoRE4INET/files/9281013/IEEE8021Q.zip)

Best regards

**Comment by Kamalakannan23** [comment]
Hi,

Thanks for the update.

Best Regards
