### ISSUE TITLE
Error occured when I, build CoRE4INET with  inet 3.8.3 in  OMNeT++ 6.0.2 

### ISSUE THREAD

**Issue by soreettihussein** [CoRE-RG/CoRE4INET#50]
I received error message: cannot find inet framework in the usual location, you have to set the path to inet in inet_proj variable. However, I put both CoRE4INET and inet in the same location (workspace: sample). 
This error message displayed when I run build project on CoRE4INET.
 Please can anyone help me!

Thanks, in advance!.

**Comment by Musteblume** [comment]
Hi,

this is an error of the make makefiles step. See the toplevel Makefile in CoRE4INET. At the very beginning its sets INET_PROJ if it is not set already. Default is that the folder named "inet" is right next to the folder named "CoRE4INET".
For more help i would need more details such as the total paths of both projects and how you built them.

Best regards

**Comment by soreettihussein** [comment]
thank you very much!! problem was solved.
