### ISSUE TITLE
Any work on 802.1Qav

### ISSUE THREAD

**Issue by mook-it** [CoRE-RG/CoRE4INET#8]
Hello 
I am interested in hearing in case  there is any on going work on IEEE 802.1Qav shaper.  I would be glad to have a try on such shaper for my simulation.

**Comment by THaeckel** [comment]
Hello mook-it,
we've implemented the reservation & shaping of IEEE 802.1Qav as part of TSN's predecessor AVB (you can check out the AVB examples to see the stream reservation working with the credit-based shaping). 
In addition, the stream reservation and shaping are compatible with our TSN models. We have implemented a TSN example (which you can find in the examples folder as well) which uses a CBS for transmission selection of priority 6 at the switch. This is relatively new and we don't have that much experience yet on running the CBS inside TSN so if you find any issues please get in touch with us.
Best,
Timo
